- hosts: localhost
  tasks:

    - name: Load Storage System Vars
      include_vars: 'properties/storage_system_properties.yml'

    - name: Load Volume Vars
      include_vars: 'properties/volume_properties.yml'

    - name: Load Host Vars
      include_vars: 'properties/host_properties.yml'

    - name: Create Volume "{{ volume_name }}"
      hpe3par_volume:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=present
        volume_name="{{ volume_name }}"
        cpg="{{ cpg }}"
        size="{{ size }}"
        snap_cpg="FC_r1"



    - name: Rename Volume "{{ volume_name }} to {{ new_name }}"
      hpe3par_volume:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=modify
        volume_name="{{ volume_name }}"
        new_name="{{ new_name }}"

    - name: Delete Volume "{{ volume_name }}"
      hpe3par_volume:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=absent
        volume_name="{{ new_name }}"
